steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      ["builds", "submit", "--tag", "gcr.io/<your project>/<service name>"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "<service name>",
        "--image",
        "gcr.io/<your project>/<service name>",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--min-instances",
        "0",
        "--allow-unauthenticated",
        "--memory",
        "1G",
      ]